### ISSUE TITLE
Issue with reporting...

### ISSUE THREAD

**Issue by vladshub** [YotpoLtd/resque-cloudwatch-monitor#1]
It seems that it doesn't work I tried `go get yotpoltd/resque-cloudwatch-monitor` and after the install it did nothing...

**Comment by avichay** [comment]
@vladshub you need to first jump 10 times on the table

**Comment by vladshub** [comment]
@avichay you used tabs as indentation instead of 2 spaces in some places  ... please take care of this :+1:

**Comment by avichay** [comment]
@vladshub weird. I'll fix it. Thanks !
